// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/job/job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_OPEN        JobStatus = 1
	JobStatus_JOB_STATUS_IN_PROGRESS JobStatus = 2
	JobStatus_JOB_STATUS_CLOSED      JobStatus = 3
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_OPEN",
		2: "JOB_STATUS_IN_PROGRESS",
		3: "JOB_STATUS_CLOSED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_OPEN":        1,
		"JOB_STATUS_IN_PROGRESS": 2,
		"JOB_STATUS_CLOSED":      3,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_job_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_job_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{0}
}

type ApplicationStatus int32

const (
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED ApplicationStatus = 0
	ApplicationStatus_APPLICATION_STATUS_PENDING     ApplicationStatus = 1
	ApplicationStatus_APPLICATION_STATUS_ACCEPTED    ApplicationStatus = 2
	ApplicationStatus_APPLICATION_STATUS_REJECTED    ApplicationStatus = 3
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "APPLICATION_STATUS_PENDING",
		2: "APPLICATION_STATUS_ACCEPTED",
		3: "APPLICATION_STATUS_REJECTED",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED": 0,
		"APPLICATION_STATUS_PENDING":     1,
		"APPLICATION_STATUS_ACCEPTED":    2,
		"APPLICATION_STATUS_REJECTED":    3,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_job_job_proto_enumTypes[1].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_proto_job_job_proto_enumTypes[1]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{1}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Budget        float64                `protobuf:"fixed64,5,opt,name=budget,proto3" json:"budget,omitempty"`
	Status        JobStatus              `protobuf:"varint,6,opt,name=status,proto3,enum=job.JobStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_job_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,3,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	CoverLetter   string                 `protobuf:"bytes,4,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	Status        ApplicationStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=job.ApplicationStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_proto_job_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Application) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *Application) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *Application) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *Application) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Budget        float64                `protobuf:"fixed64,4,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_proto_job_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_proto_job_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{3}
}

func (x *CreateJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_job_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_job_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_job_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_job_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ApplyToJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	CoverLetter   string                 `protobuf:"bytes,3,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyToJobRequest) Reset() {
	*x = ApplyToJobRequest{}
	mi := &file_proto_job_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyToJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyToJobRequest) ProtoMessage() {}

func (x *ApplyToJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyToJobRequest.ProtoReflect.Descriptor instead.
func (*ApplyToJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyToJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ApplyToJobRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *ApplyToJobRequest) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

type ApplyToJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *Application           `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyToJobResponse) Reset() {
	*x = ApplyToJobResponse{}
	mi := &file_proto_job_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyToJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyToJobResponse) ProtoMessage() {}

func (x *ApplyToJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyToJobResponse.ProtoReflect.Descriptor instead.
func (*ApplyToJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyToJobResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type AcceptFreelancerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFreelancerRequest) Reset() {
	*x = AcceptFreelancerRequest{}
	mi := &file_proto_job_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFreelancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFreelancerRequest) ProtoMessage() {}

func (x *AcceptFreelancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFreelancerRequest.ProtoReflect.Descriptor instead.
func (*AcceptFreelancerRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptFreelancerRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcceptFreelancerRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type AcceptFreelancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Application   *Application           `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFreelancerResponse) Reset() {
	*x = AcceptFreelancerResponse{}
	mi := &file_proto_job_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFreelancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFreelancerResponse) ProtoMessage() {}

func (x *AcceptFreelancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFreelancerResponse.ProtoReflect.Descriptor instead.
func (*AcceptFreelancerResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptFreelancerResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *AcceptFreelancerResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_proto_job_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_proto_job_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{13}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_proto_job_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CompleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobResponse) Reset() {
	*x = CompleteJobResponse{}
	mi := &file_proto_job_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobResponse) ProtoMessage() {}

func (x *CompleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_proto_job_job_proto protoreflect.FileDescriptor

const file_proto_job_job_proto_rawDesc = "" +
	"\n" +
	"\x13proto/job/job.proto\x12\x03job\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06budget\x18\x05 \x01(\x01R\x06budget\x12&\n" +
	"\x06status\x18\x06 \x01(\x0e2\x0e.job.JobStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe7\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12#\n" +
	"\rfreelancer_id\x18\x03 \x01(\tR\ffreelancerId\x12!\n" +
	"\fcover_letter\x18\x04 \x01(\tR\vcoverLetter\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.job.ApplicationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x7f\n" +
	"\x10CreateJobRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x01R\x06budget\"/\n" +
	"\x11CreateJobResponse\x12\x1a\n" +
	"\x03job\x18\x01 \x01(\v2\b.job.JobR\x03job\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x0eGetJobResponse\x12\x1a\n" +
	"\x03job\x18\x01 \x01(\v2\b.job.JobR\x03job\"_\n" +
	"\x0fListJobsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"F\n" +
	"\x10ListJobsResponse\x12\x1c\n" +
	"\x04jobs\x18\x01 \x03(\v2\b.job.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"r\n" +
	"\x11ApplyToJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12!\n" +
	"\fcover_letter\x18\x03 \x01(\tR\vcoverLetter\"H\n" +
	"\x12ApplyToJobResponse\x122\n" +
	"\vapplication\x18\x01 \x01(\v2\x10.job.ApplicationR\vapplication\"W\n" +
	"\x17AcceptFreelancerRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\"j\n" +
	"\x18AcceptFreelancerResponse\x12\x1a\n" +
	"\x03job\x18\x01 \x01(\v2\b.job.JobR\x03job\x122\n" +
	"\vapplication\x18\x02 \x01(\v2\x10.job.ApplicationR\vapplication\"0\n" +
	"\x17ListApplicationsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"P\n" +
	"\x18ListApplicationsResponse\x124\n" +
	"\fapplications\x18\x01 \x03(\v2\x10.job.ApplicationR\fapplications\"+\n" +
	"\x12CompleteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"1\n" +
	"\x13CompleteJobResponse\x12\x1a\n" +
	"\x03job\x18\x01 \x01(\v2\b.job.JobR\x03job*o\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fJOB_STATUS_OPEN\x10\x01\x12\x1a\n" +
	"\x16JOB_STATUS_IN_PROGRESS\x10\x02\x12\x15\n" +
	"\x11JOB_STATUS_CLOSED\x10\x03*\x99\x01\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAPPLICATION_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_ACCEPTED\x10\x02\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_REJECTED\x10\x032\xd7\x03\n" +
	"\n" +
	"JobService\x12:\n" +
	"\tCreateJob\x12\x15.job.CreateJobRequest\x1a\x16.job.CreateJobResponse\x121\n" +
	"\x06GetJob\x12\x12.job.GetJobRequest\x1a\x13.job.GetJobResponse\x127\n" +
	"\bListJobs\x12\x14.job.ListJobsRequest\x1a\x15.job.ListJobsResponse\x12=\n" +
	"\n" +
	"ApplyToJob\x12\x16.job.ApplyToJobRequest\x1a\x17.job.ApplyToJobResponse\x12O\n" +
	"\x10AcceptFreelancer\x12\x1c.job.AcceptFreelancerRequest\x1a\x1d.job.AcceptFreelancerResponse\x12O\n" +
	"\x10ListApplications\x12\x1c.job.ListApplicationsRequest\x1a\x1d.job.ListApplicationsResponse\x12@\n" +
	"\vCompleteJob\x12\x17.job.CompleteJobRequest\x1a\x18.job.CompleteJobResponseB>Z<github.com/yourname/freelance-platform/job-service/proto/jobb\x06proto3"

var (
	file_proto_job_job_proto_rawDescOnce sync.Once
	file_proto_job_job_proto_rawDescData []byte
)

func file_proto_job_job_proto_rawDescGZIP() []byte {
	file_proto_job_job_proto_rawDescOnce.Do(func() {
		file_proto_job_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_job_proto_rawDesc), len(file_proto_job_job_proto_rawDesc)))
	})
	return file_proto_job_job_proto_rawDescData
}

var file_proto_job_job_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_job_job_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_job_job_proto_goTypes = []any{
	(JobStatus)(0),                   // 0: job.JobStatus
	(ApplicationStatus)(0),           // 1: job.ApplicationStatus
	(*Job)(nil),                      // 2: job.Job
	(*Application)(nil),              // 3: job.Application
	(*CreateJobRequest)(nil),         // 4: job.CreateJobRequest
	(*CreateJobResponse)(nil),        // 5: job.CreateJobResponse
	(*GetJobRequest)(nil),            // 6: job.GetJobRequest
	(*GetJobResponse)(nil),           // 7: job.GetJobResponse
	(*ListJobsRequest)(nil),          // 8: job.ListJobsRequest
	(*ListJobsResponse)(nil),         // 9: job.ListJobsResponse
	(*ApplyToJobRequest)(nil),        // 10: job.ApplyToJobRequest
	(*ApplyToJobResponse)(nil),       // 11: job.ApplyToJobResponse
	(*AcceptFreelancerRequest)(nil),  // 12: job.AcceptFreelancerRequest
	(*AcceptFreelancerResponse)(nil), // 13: job.AcceptFreelancerResponse
	(*ListApplicationsRequest)(nil),  // 14: job.ListApplicationsRequest
	(*ListApplicationsResponse)(nil), // 15: job.ListApplicationsResponse
	(*CompleteJobRequest)(nil),       // 16: job.CompleteJobRequest
	(*CompleteJobResponse)(nil),      // 17: job.CompleteJobResponse
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_proto_job_job_proto_depIdxs = []int32{
	0,  // 0: job.Job.status:type_name -> job.JobStatus
	18, // 1: job.Job.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: job.Job.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: job.Application.status:type_name -> job.ApplicationStatus
	18, // 4: job.Application.created_at:type_name -> google.protobuf.Timestamp
	2,  // 5: job.CreateJobResponse.job:type_name -> job.Job
	2,  // 6: job.GetJobResponse.job:type_name -> job.Job
	2,  // 7: job.ListJobsResponse.jobs:type_name -> job.Job
	3,  // 8: job.ApplyToJobResponse.application:type_name -> job.Application
	2,  // 9: job.AcceptFreelancerResponse.job:type_name -> job.Job
	3,  // 10: job.AcceptFreelancerResponse.application:type_name -> job.Application
	3,  // 11: job.ListApplicationsResponse.applications:type_name -> job.Application
	2,  // 12: job.CompleteJobResponse.job:type_name -> job.Job
	4,  // 13: job.JobService.CreateJob:input_type -> job.CreateJobRequest
	6,  // 14: job.JobService.GetJob:input_type -> job.GetJobRequest
	8,  // 15: job.JobService.ListJobs:input_type -> job.ListJobsRequest
	10, // 16: job.JobService.ApplyToJob:input_type -> job.ApplyToJobRequest
	12, // 17: job.JobService.AcceptFreelancer:input_type -> job.AcceptFreelancerRequest
	14, // 18: job.JobService.ListApplications:input_type -> job.ListApplicationsRequest
	16, // 19: job.JobService.CompleteJob:input_type -> job.CompleteJobRequest
	5,  // 20: job.JobService.CreateJob:output_type -> job.CreateJobResponse
	7,  // 21: job.JobService.GetJob:output_type -> job.GetJobResponse
	9,  // 22: job.JobService.ListJobs:output_type -> job.ListJobsResponse
	11, // 23: job.JobService.ApplyToJob:output_type -> job.ApplyToJobResponse
	13, // 24: job.JobService.AcceptFreelancer:output_type -> job.AcceptFreelancerResponse
	15, // 25: job.JobService.ListApplications:output_type -> job.ListApplicationsResponse
	17, // 26: job.JobService.CompleteJob:output_type -> job.CompleteJobResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_job_job_proto_init() }
func file_proto_job_job_proto_init() {
	if File_proto_job_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_job_proto_rawDesc), len(file_proto_job_job_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_job_proto_goTypes,
		DependencyIndexes: file_proto_job_job_proto_depIdxs,
		EnumInfos:         file_proto_job_job_proto_enumTypes,
		MessageInfos:      file_proto_job_job_proto_msgTypes,
	}.Build()
	File_proto_job_job_proto = out.File
	file_proto_job_job_proto_goTypes = nil
	file_proto_job_job_proto_depIdxs = nil
}
