services:
  api-gateway:
    build: .
    command: ["./gateway"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      GATEWAY_HTTP_ADDR: ":8080"
      JOB_SERVICE_GRPC_ADDR: "job-service:50052"
    depends_on:
      job-service:
        condition: service_started

  job-service:
    build: .
    ports:
      - "50052:50052"
    restart: unless-stopped
    environment:
      GRPC_PORT: ":50052"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/jobdb?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      RABBITMQ_EXCHANGE: "jobs"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: ""   # fill in
      SMTP_PASSWORD: ""   # fill in (Gmail App Password)
      SMTP_FROM: ""       # fill in
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    image: migrate/migrate:v4.18.1
    volumes:
      - ./migrations:/migrations:ro
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/jobdb?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
